### ISSUE TITLE
Consider refactoring away most namespaces

### ISSUE THREAD

**Issue by Bronsa** [mylesmegyesi/clojure.core#35]
Hi,
I've been watching the activity on this repo hoping that one day this could be made into another piace in the tools.reader/tools.analyzer[.jvm]/tools.emitter group of libraries that will help towards a CinC implementation, I like the way this library is going and I am considering starting to contribute when I'll have some free time.

I have a couple of complains though:
* I really don't like the big amount of namespaces that are getting created, there's no point to them, I'd propose grouping all the protocols from each on their own namespace to all the namespaces in a `clojure.lang.protocols` namespace and all the "wrapping" namespaces in a `clojure.core'` namespace (e.g get rid of namespaces `clojure.lang.deref` or `clojure.lang.map-entry`)
* The current way of creating partial/extensible reimplementations for deftypes looks horrible (sorry :)). I've been down the road of reimplementing the clojure corelib before deciding to focus on the reader/compiler and I wrote [neurotic](https://github.com/Bronsa/neurotic) for this purpose, you can see an example of how to define partial implementations reusable in deftypes [here](https://github.com/Bronsa/brochure/blob/master/src/clojure/lang/traits.clj#L8-L39) and how to actually use it in a deftype [here](https://github.com/Bronsa/brochure/blob/master/src/clojure/lang/atom.clj#L10-L32).

What do you think?

**Comment by sdegutis** [comment]
:+1:

**Comment by patrickgombert** [comment]
Closing because we now have `clojure.lang.protocols` and `clojure.lang.deftype`
